services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: hindsight_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d hindsight_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hindsight-ai
  traefik:
    image: traefik:v3.4.4
    container_name: traefik
    profiles: ["prod"]
    environment:
      - CLOUDFLARE_DNS_EMAIL=${CLOUDFLARE_DNS_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    command:
      - "--configFile=/config/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/config:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - hindsight-ai
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.hindsight-ai.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
    depends_on:
      - oauth2-proxy

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    profiles: ["prod"]
    environment:
      OAUTH2_PROXY_PROVIDER: google
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_REDIRECT_URL: https://auth.hindsight-ai.com/oauth2/callback
      OAUTH2_PROXY_UPSTREAMS: static://204
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      OAUTH2_PROXY_COOKIE_SAMESITE: none
      OAUTH2_PROXY_COOKIE_SECURE: true
      OAUTH2_PROXY_COOKIE_DOMAINS: .hindsight-ai.com
      OAUTH2_PROXY_CSRF_COOKIE_DOMAINS: .hindsight-ai.com
      OAUTH2_PROXY_WHITELIST_DOMAINS: .hindsight-ai.com,.google.com
      OAUTH2_PROXY_REVERSE_PROXY: true
      OAUTH2_PROXY_SET_XAUTHREQUEST: true
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: true
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE: /etc/oauth2-proxy/authorized_emails.txt
      OAUTH2_PROXY_LOGOUT_REDIRECT_URL: https://accounts.google.com/Logout
    command:
      - "--custom-templates-dir=/templates"
    networks:
      - hindsight-ai
    volumes:
      - ./authorized_emails.txt:/etc/oauth2-proxy/authorized_emails.txt:ro
      - ./templates:/templates:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth2-proxy.rule=(Host(`auth.hindsight-ai.com`)) && PathPrefix(`/oauth2`)"
      - "traefik.http.routers.oauth2-proxy.entrypoints=websecure"
      - "traefik.http.routers.oauth2-proxy.tls.certresolver=letsencrypt"
      - "traefik.http.routers.oauth2-proxy.service=oauth2-svc@docker"
      - "traefik.http.services.oauth2-svc.loadbalancer.server.port=4180"

  hindsight-service:
    image: ${HINDSIGHT_SERVICE_IMAGE:-hindsight-service:latest}
    build:
      context: ./apps/hindsight-service
      dockerfile: Dockerfile
    container_name: hindsight-service
    networks:
      - hindsight-ai
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/hindsight_db
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL_NAME: ${LLM_MODEL_NAME}
      CONSOLIDATION_BATCH_SIZE: ${CONSOLIDATION_BATCH_SIZE}
      FALLBACK_SIMILARITY_THRESHOLD: ${FALLBACK_SIMILARITY_THRESHOLD}
    depends_on:
      db:
        condition: service_healthy
    # No Traefik exposure; API is accessed via dashboard /api proxy

  hindsight-dashboard:
    image: ${HINDSIGHT_DASHBOARD_IMAGE:-hindsight-dashboard:latest}
    build:
      context: ./apps/hindsight-dashboard
      dockerfile: Dockerfile
    container_name: hindsight-dashboard
    # Frontend will call relative "/api" and Nginx will proxy to backend
    depends_on:
      - hindsight-service
    networks:
      - hindsight-ai
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hindsight-dashboard-router.rule=Host(`app.hindsight-ai.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.hindsight-dashboard-router.entrypoints=websecure"
      - "traefik.http.routers.hindsight-dashboard-router.tls.certresolver=letsencrypt"
      # Protect the dashboard with OAuth2 forward auth
      - "traefik.http.routers.hindsight-dashboard-router.middlewares=secure-headers@file,oauth-middleware@file,auth-errors@file"
      - "traefik.http.routers.hindsight-dashboard-router.service=hindsight-dashboard-svc@docker"
      - "traefik.http.services.hindsight-dashboard-svc.loadbalancer.server.port=80"
      # Public router for manifest.json to prevent 401 during browser prefetch
      - "traefik.http.routers.hindsight-dashboard-manifest.rule=Host(`app.hindsight-ai.com`) && Path(`/manifest.json`)"
      - "traefik.http.routers.hindsight-dashboard-manifest.entrypoints=websecure"
      - "traefik.http.routers.hindsight-dashboard-manifest.tls.certresolver=letsencrypt"
      - "traefik.http.routers.hindsight-dashboard-manifest.service=hindsight-dashboard-svc@docker"
      - "traefik.http.routers.hindsight-dashboard-manifest.middlewares=secure-headers@file"
      - "traefik.http.routers.hindsight-dashboard-manifest.priority=1000"
      # Also allow favicon without auth to prevent browser noise
      - "traefik.http.routers.hindsight-dashboard-favicon.rule=Host(`app.hindsight-ai.com`) && Path(`/favicon.ico`)"
      - "traefik.http.routers.hindsight-dashboard-favicon.entrypoints=websecure"
      - "traefik.http.routers.hindsight-dashboard-favicon.tls.certresolver=letsencrypt"
      - "traefik.http.routers.hindsight-dashboard-favicon.service=hindsight-dashboard-svc@docker"
      - "traefik.http.routers.hindsight-dashboard-favicon.middlewares=secure-headers@file"
      - "traefik.http.routers.hindsight-dashboard-favicon.priority=1000"

  hindsight-copilot-assistant:
    profiles: ["copilot"]
    image: ${HINDSIGHT_COPILOT_ASSISTANT_IMAGE:-hindsight-copilot-assistant:latest}
    build:
      context: ./apps/hindsight-copilot-assistant
      dockerfile: Dockerfile
    container_name: hindsight-copilot-assistant
    networks:
      - hindsight-ai
    ports:
      - "3001:3000"
    depends_on:
      - hindsight-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hindsight-copilot-assistant-router.rule=Host(`copilot.hindsight-ai.com`)"
      - "traefik.http.routers.hindsight-copilot-assistant-router.entrypoints=websecure"
      - "traefik.http.routers.hindsight-copilot-assistant-router.tls.certresolver=letsencrypt"
      - "traefik.http.routers.hindsight-copilot-assistant-router.service=hindsight-copilot-assistant-svc@docker"
      - "traefik.http.services.hindsight-copilot-assistant-svc.loadbalancer.server.port=3001"

networks:
  hindsight-ai:
    driver: bridge

volumes:
  db_data:
