services:
  # Override the db service to expose port 5432 for local access if needed
  db:
    ports:
      - "5432:5432"

  # Override the hindsight-service to expose port 8000 directly
  hindsight-service:
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_BASE_URL: ${APP_BASE_URL}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      DEV_MODE: ${DEV_MODE}
      BUILD_SHA: ${BACKEND_BUILD_SHA}
      BUILD_TIMESTAMP: ${BUILD_TIMESTAMP}
      IMAGE_TAG: ${BACKEND_IMAGE_TAG}
      VERSION: ${BACKEND_VERSION}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL_NAME: ${LLM_MODEL_NAME}
      CONSOLIDATION_BATCH_SIZE: ${CONSOLIDATION_BATCH_SIZE}
      FALLBACK_SIMILARITY_THRESHOLD: ${FALLBACK_SIMILARITY_THRESHOLD}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      SUPPORT_CONTACT_MIN_INTERVAL_SECONDS: ${SUPPORT_CONTACT_MIN_INTERVAL_SECONDS}
      PRUNING_BATCH_SIZE: ${PRUNING_BATCH_SIZE}
      PRUNING_MAX_ITERATIONS: ${PRUNING_MAX_ITERATIONS}
      LOG_LEVEL: ${LOG_LEVEL}
    develop:
      watch:
        - path: ./apps/hindsight-service
          action: rebuild

  # Override the hindsight-dashboard to expose port 3000 directly
  hindsight-dashboard:
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      VITE_DEV_MODE: ${DEV_MODE}
    develop:
      watch:
        - path: ./apps/hindsight-dashboard
          action: rebuild

  # Add hindsight-copilot-assistant service
  hindsight-copilot-assistant:
    profiles: ["copilot"]
    build:
      context: ./apps/hindsight-copilot-assistant
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      LLM_API_KEY: ${LLM_API_KEY}
    networks:
      - hindsight-ai
    develop:
      watch:
        - path: ./apps/hindsight-copilot-assistant
          action: rebuild
