services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: hindsight_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
