"""Add pg_trgm extension for fuzzy search

Revision ID: 2a9c8674c949
Revises: 57a3b3cd5572
Create Date: 2025-06-09 21:16:28.192589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9c8674c949'
down_revision: Union[str, None] = '57a3b3cd5572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_index('idx_agent_transcripts_agent_id', 'agent_transcripts', ['agent_id'], unique=False)
    op.create_index('idx_agent_transcripts_conversation_id', 'agent_transcripts', ['conversation_id'], unique=False)
    op.create_index('idx_keywords_keyword_text', 'keywords', ['keyword_text'], unique=False)
    op.create_index('idx_memory_blocks_agent_id', 'memory_blocks', ['agent_id'], unique=False)
    op.create_index('idx_memory_blocks_conversation_id', 'memory_blocks', ['conversation_id'], unique=False)
    op.create_index('idx_memory_blocks_timestamp', 'memory_blocks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_memory_blocks_timestamp', table_name='memory_blocks')
    op.drop_index('idx_memory_blocks_conversation_id', table_name='memory_blocks')
    op.drop_index('idx_memory_blocks_agent_id', table_name='memory_blocks')
    op.drop_index('idx_keywords_keyword_text', table_name='keywords')
    op.drop_index('idx_agent_transcripts_conversation_id', table_name='agent_transcripts')
    op.drop_index('idx_agent_transcripts_agent_id', table_name='agent_transcripts')
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    # ### end Alembic commands ###
