"""add beta access table

Revision ID: 58d9df7d9301
Revises: 20250916_convert_org_inv
Create Date: 2025-09-16 20:12:27.265532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d9df7d9301'
down_revision: Union[str, None] = '20250916_convert_org_inv'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'beta_access_requests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('email', sa.Text(), nullable=False),
        # default on DB to avoid failing when creating rows from existing code paths
        sa.Column('status', sa.Text(), nullable=False, server_default=sa.text("'pending'")),
        sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reviewer_email', sa.Text(), nullable=True),
        sa.Column('decision_reason', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_agents_org_only'), table_name='agents', postgresql_where="((visibility_scope)::text = 'organization'::text)")
    op.drop_index(op.f('idx_keywords_org_only'), table_name='keywords', postgresql_where="((visibility_scope)::text = 'organization'::text)")
    op.drop_index(op.f('idx_memory_blocks_org_only'), table_name='memory_blocks', postgresql_where="((visibility_scope)::text = 'organization'::text)")
    # add users.beta_access_status with a server default so existing rows get a value
    op.add_column('users', sa.Column('beta_access_status', sa.String(), nullable=False, server_default=sa.text("'pending'")))
    # remove the server default to mirror the Python model default behavior
    op.alter_column('users', 'beta_access_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'beta_access_status')
    op.create_index(op.f('idx_memory_blocks_org_only'), 'memory_blocks', ['organization_id'], unique=False, postgresql_where="((visibility_scope)::text = 'organization'::text)")
    op.create_index(op.f('idx_keywords_org_only'), 'keywords', ['organization_id'], unique=False, postgresql_where="((visibility_scope)::text = 'organization'::text)")
    op.create_index(op.f('idx_agents_org_only'), 'agents', ['organization_id'], unique=False, postgresql_where="((visibility_scope)::text = 'organization'::text)")
    op.drop_table('beta_access_requests')
    # ### end Alembic commands ###
