"""Add consolidation_suggestions table

Revision ID: 975d4a80651a
Revises: 2a9c8674c949
Create Date: 2025-06-11 21:32:45.291902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '975d4a80651a'
down_revision: Union[str, None] = '2a9c8674c949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consolidation_suggestions',
    sa.Column('suggestion_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=False),
    sa.Column('suggested_lessons_learned', sa.Text(), nullable=False),
    sa.Column('suggested_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('original_memory_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('suggestion_id'),
    sa.UniqueConstraint('group_id')
    )
    op.create_index('idx_consolidation_suggestions_group_id', 'consolidation_suggestions', ['group_id'], unique=False)
    op.create_index('idx_consolidation_suggestions_status', 'consolidation_suggestions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_consolidation_suggestions_status', table_name='consolidation_suggestions')
    op.drop_index('idx_consolidation_suggestions_group_id', table_name='consolidation_suggestions')
    op.drop_table('consolidation_suggestions')
    # ### end Alembic commands ###
