"""Add archived column to MemoryBlock

Revision ID: bdec54c35ae4
Revises: 975d4a80651a
Create Date: 2025-06-11 23:29:07.280912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdec54c35ae4'
down_revision: Union[str, None] = '975d4a80651a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_blocks', sa.Column('archived', sa.Boolean(), nullable=True))
    # Set existing rows to False (not archived)
    op.execute("UPDATE memory_blocks SET archived = FALSE WHERE archived IS NULL")
    # Alter column to be non-nullable and set a default for new rows
    op.alter_column('memory_blocks', 'archived',
               existing_type=sa.Boolean(),
               nullable=False,
               server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_blocks', 'archived')
    # ### end Alembic commands ###
