apiVersion: apps/v1
kind: Deployment
metadata:
  name: hindsight-service-deployment
  labels:
    app: hindsight-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hindsight-service
  template:
    metadata:
      labels:
        app: hindsight-service
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      initContainers:
        - name: migrate-db
          image: ghcr.io/YOUR_GITHUB_USERNAME/hindsight-service:latest # Use the same service image for migrations
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Waiting for PostgreSQL to be ready (timeout 300s)..."
              TIMEOUT=300
              until pg_isready -h postgres-service -p 5432 -U user; do
                echo "PostgreSQL is unavailable - sleeping"
                sleep 2
                TIMEOUT=$((TIMEOUT-2))
                if [ $TIMEOUT -le 0 ]; then
                  echo "PostgreSQL did not become ready within the timeout period. Exiting."
                  exit 1
                fi
              done
              echo "PostgreSQL is up - running migrations"
              alembic upgrade head
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-service:5432/hindsight_db"
      containers:
        - name: hindsight-service
          image: ghcr.io/YOUR_GITHUB_USERNAME/hindsight-service:latest # This will be updated by GitHub Actions
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-service:5432/hindsight_db"
            # Add other necessary environment variables here, e.g., LLM_API_KEY
            # For production, consider using Kubernetes Secrets for sensitive data
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hindsight-secrets
                  key: LLM_API_KEY
            - name: LLM_MODEL_NAME
              value: "gemini-2.5-flash-preview-05-20"
            - name: CONSOLIDATION_BATCH_SIZE
              value: "100"
            - name: FALLBACK_SIMILARITY_THRESHOLD
              value: "0.4"
          imagePullPolicy: Always # Ensure the latest image is pulled
