apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hindsight-service-ingress
spec:
  entryPoints:
    - websecure # Assuming Traefik is configured for HTTPS
  routes:
    - match: HostRegexp(`{host:.+}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: hindsight-service-service
          port: 8000
