apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hindsight-service-ingress
spec:
  entryPoints:
    - web # Using the 'web' entry point for HTTP access
  routes:
    - match: Host(`46.62.141.65`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: hindsight-service-service
          port: 8000
