apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hindsight-service-ingress
spec:
  entryPoints:
    - web # HTTP entry point for redirection
    - websecure # HTTPS entry point
  routes:
    - match: Host(`hindsight-ai.com`) || Host(`www.hindsight-ai.com`)
      kind: Rule
      services:
        - name: hindsight-service-service
          port: 8000
      middlewares:
        - name: redirect-to-https
        - name: oauth2-proxy-auth@kubernetescrd # Apply OAuth2 Proxy authentication
  tls:
    secretName: hindsight-tls-secret # Name of the secret containing your TLS certificate and key
