apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-auth
  namespace: default # Explicitly define namespace for strict Traefik referencing
spec:
  forwardAuth:
    address: http://oauth2-proxy-service:4180/oauth2/auth
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Access-Token
      - X-Auth-Request-Preferred-Username
    tls:
      insecureSkipVerify: true # Only if oauth2-proxy uses self-signed certs, otherwise remove
