# ./config/dynamic.yml

http:
  middlewares:
    oauth-middleware:
      forwardAuth:
        address: "http://oauth2-proxy:4180/oauth2/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-Request-User"
          - "X-Auth-Request-Email"
          - "X-Auth-Request-Access-Token"
    cors-headers:
      headers:
        customResponseHeaders:
          Access-Control-Allow-Origin: "*"
          Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
          Access-Control-Allow-Headers: "Content-Type, Authorization"
          Access-Control-Allow-Credentials: "true"
        addVaryHeader: true # Re-add addVaryHeader for good measure
