# ./config/dynamic.yml

http:
  middlewares:
    oauth-middleware:
      forwardAuth:
        address: "http://oauth2-proxy:4180/oauth2/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-Request-User"
          - "X-Auth-Request-Email"
          - "X-Auth-Request-Access-Token"
    cors-headers:
      headers:
        # Use Traefik's built-in CORS fields instead of wildcard headers.
        accessControlAllowOriginList:
          - "https://dashboard.hindsight-ai.com"
          - "https://hindsight-ai.com"
          - "http://localhost:3000"
          - "http://localhost:3001"
          - "http://localhost"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
        accessControlAllowCredentials: true
        addVaryHeader: true
