name: CI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hindsight-service-tests:
    name: Hindsight Service (pytest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/hindsight-service
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Run tests with coverage (XML)
        run: >-
          uv run --with pytest-cov \
          pytest --maxfail=1 \
          --cov=core --cov-report=term --cov-report=xml:coverage.xml

      - name: Upload Python coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: apps/hindsight-service/coverage.xml
          flags: service
          name: service-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  dashboard-tests:
    name: Dashboard (Jest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/hindsight-dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/hindsight-dashboard/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Jest (coverage)
        run: npm run test:coverage -- --ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: apps/hindsight-dashboard/coverage/lcov.info
          flags: dashboard
          name: dashboard-lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v5
        with:
          name: dashboard-coverage
          path: apps/hindsight-dashboard/coverage

  # No deploy in this workflow; deployment lives in deploy.yml and includes its own test gates.
